name: Ci Dev Branch
on:
  workflow_dispatch:
  push:
    branches:
      - "rd*"
      - "!main"
jobs:
  common:
    uses: testVinaycicd/github-resuable-actions/.github/workflows/ci-dev-br.yml@main
    with:
      component_name: cart
      app_type: nodejs
